name: CI for Producer and Consumer

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'

permissions:
  contents: read

jobs:
  build-producer:
    name: Build Producer
    runs-on: ubuntu-latest

    steps:
      # ì½”ë“œ ì²´í¬ì•„ì›ƒ
      - uses: actions/checkout@v4

      # JDK ì„¤ì •
      - name: â˜•ï¸ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Producer ë¹Œë“œ
      - name: ğŸ˜ Build Producer with Gradle
        working-directory: ./producer
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test --stacktrace

  build-consumer:
    name: Build Consumer
    runs-on: ubuntu-latest

    steps:
      # ì½”ë“œ ì²´í¬ì•„ì›ƒ
      - uses: actions/checkout@v4

      # JDK ì„¤ì •
      - name: â˜•ï¸ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Consumer ë¹Œë“œ
      - name: ğŸ˜ Build Consumer with Gradle
        working-directory: ./consumer
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test --stacktrace