name: CI for Producer and Consumer

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'

permissions:
  contents: read

jobs:
  build-producer:
    name: Build Producer
    runs-on: ubuntu-latest

    steps:
      # ì½”ë“œ ì²´í¬ì•„ì›ƒ
      - uses: actions/checkout@v4

      # JDK ì„¤ì •
      - name: â˜•ï¸ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # í™˜ê²½ ë³€ìˆ˜ ë“±ë¡
      - name: ğŸ” Set environment variables for Producer
        run: |
          echo "SPRING_DATASOURCE_DRIVER_CLASS_NAME=${{ secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME }}" > .env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> .env
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> .env
          echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> .env
          echo "NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}" >> .env
          echo "NAVER_LOCATION_SEARCH_URL=${{ secrets.NAVER_LOCATION_SEARCH_URL }}" >> .env
          echo "AWS_EC2_REDIS_HOST=${{ secrets.AWS_EC2_REDIS_HOST }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env

      # Producer ë¹Œë“œ ë° í…ŒìŠ¤íŠ¸
      - name: ğŸ˜ Build and Test Producer with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew :producer:clean :producer:build :producer:test --stacktrace

  build-consumer:
    name: Build Consumer
    runs-on: ubuntu-latest

    steps:
      # ì½”ë“œ ì²´í¬ì•„ì›ƒ
      - uses: actions/checkout@v4

      # JDK ì„¤ì •
      - name: â˜•ï¸ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # í™˜ê²½ ë³€ìˆ˜ ë“±ë¡
      - name: ğŸ” Set environment variables for Consumer
        run: |
          echo "SPRING_DATASOURCE_DRIVER_CLASS_NAME=${{ secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME }}" > .env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> .env
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> .env
          echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> .env
          echo "NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}" >> .env
          echo "NAVER_LOCATION_SEARCH_URL=${{ secrets.NAVER_LOCATION_SEARCH_URL }}" >> .env
          echo "AWS_EC2_REDIS_HOST=${{ secrets.AWS_EC2_REDIS_HOST }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env

      # Consumer ë¹Œë“œ ë° í…ŒìŠ¤íŠ¸
      - name: ğŸ˜ Build and Test Consumer with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew :consumer:clean :consumer:build :consumer:test --stacktrace